// File-content templates for the scaffolded self-host folder. Pure string
// builders — no I/O — so they are trivially testable.

/** Engines the scaffolder can emit a client snippet for. */
export const ENGINES = ["babylon", "babylon-lite", "three", "r3f", "playcanvas", "aframe"] as const;

export type Engine = (typeof ENGINES)[number];

/** npm package a developer installs in their app for a given engine. */
export const ENGINE_PACKAGE: Record<Engine, string> = {
  babylon: "@uptimizr/babylon",
  "babylon-lite": "@uptimizr/babylon-lite",
  three: "@uptimizr/three",
  r3f: "@uptimizr/r3f",
  playcanvas: "@uptimizr/playcanvas",
  aframe: "@uptimizr/aframe",
};

const DEFAULT_PORT = 4318;

/** The collector endpoint a freshly-scaffolded local self-host listens on. */
export function localEndpoint(port: number = DEFAULT_PORT): string {
  return `http://localhost:${port}`;
}

export function renderPackageJson(folderName: string, projectName: string): string {
  const pkg = {
    name: folderName,
    version: "0.0.0",
    private: true,
    type: "module",
    description: `Uptimizr self-host for "${projectName}" (DuckDB, no Docker).`,
    scripts: {
      // First-run setup: mint the first project + API key and ensure the store
      // is migrated. The generated .env already holds the visitor-hash secret.
      setup: `uptimizr init ${JSON.stringify(projectName)}`,
      // Run the ingestion + query API (reads the generated .env).
      start: "uptimizr serve",
      "new-project": "uptimizr new-project",
      migrate: "uptimizr migrate",
    },
    dependencies: {
      "@uptimizr/collector-server": "^0.2.1",
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

export function renderEnv(secret: string, port: number = DEFAULT_PORT): string {
  return `${[
    "# Uptimizr collector configuration (generated by create-uptimizr).",
    "# OSS default store is DuckDB — no Docker, no external database.",
    "# Keep this file private; it holds your visitor-hash secret.",
    "",
    `VISITOR_HASH_SECRET=${secret}`,
    "COLLECTOR_STORE=duckdb",
    "DUCKDB_PATH=./data/uptimizr.duckdb",
    `COLLECTOR_PORT=${port}`,
    "",
    "# Browser origins allowed to send analytics (comma-separated). Add your app's",
    "# dev + production origins here.",
    "COLLECTOR_CORS_ORIGINS=http://localhost:5173",
    "",
    "# All-in-one (optional): point at a static dashboard build to serve the UI",
    "# from this same process. See @uptimizr/dashboard.",
    "# COLLECTOR_DASHBOARD_DIR=./dashboard",
  ].join("\n")}\n`;
}

export function renderGitignore(): string {
  return `${["node_modules/", ".env", "data/"].join("\n")}\n`;
}

/** A ready-to-paste client snippet for the chosen engine. */
export function renderClientSnippet(engine: Engine, port: number = DEFAULT_PORT): string {
  const endpoint = localEndpoint(port);
  const pkg = ENGINE_PACKAGE[engine];
  const header = [
    `// Wire Uptimizr into your ${engine} app.`,
    `// Install the connector in your app:  npm install ${pkg}`,
    `// Replace PROJECT_ID with the id printed by \`npm run setup\`.`,
    "",
  ].join("\n");

  switch (engine) {
    case "babylon":
      return `${header}import { trackScene } from "${pkg}";

trackScene(scene, {
  projectId: "PROJECT_ID",
  endpoint: "${endpoint}",
});
`;
    case "babylon-lite":
      return `${header}import { trackScene } from "${pkg}";

trackScene(scene, camera, canvas, {
  projectId: "PROJECT_ID",
  endpoint: "${endpoint}",
});
`;
    case "three":
      return `${header}import { trackScene } from "${pkg}";

trackScene(scene, camera, renderer, {
  projectId: "PROJECT_ID",
  endpoint: "${endpoint}",
});
`;
    case "playcanvas":
      return `${header}import { trackScene } from "${pkg}";

trackScene(app, cameraEntity, {
  projectId: "PROJECT_ID",
  endpoint: "${endpoint}",
});
`;
    case "r3f":
      return `${header}import { Uptimizr } from "${pkg}";

// Render inside your <Canvas> tree:
//   <Canvas>
//     <Uptimizr projectId="PROJECT_ID" endpoint="${endpoint}" />
//     {/* ...your scene... */}
//   </Canvas>
`;
    case "aframe":
      return `${header}// Import once to register the component, then add the attribute to <a-scene>:
import "${pkg}";

// <a-scene uptimizr="projectId: PROJECT_ID; collector: ${endpoint}">
//   <!-- ...your scene... -->
// </a-scene>
`;
  }
}

export function renderReadme(
  folderName: string,
  projectName: string,
  engine: Engine,
  port: number = DEFAULT_PORT,
): string {
  const endpoint = localEndpoint(port);
  return `# ${folderName}

A Docker-free, single-file (DuckDB) self-host of the Uptimizr OSS 3D-analytics
collector, scaffolded for **${projectName}**.

## Quick start

\`\`\`bash
npm install      # install the collector
npm run setup    # mint your first project + API key (printed once)
npm start        # ingestion + query API on ${endpoint}
\`\`\`

\`npm run setup\` prints a **projectId**, a one-time **API key**, and the
**endpoint**. Give the projectId + endpoint to your app's connector (see
[\`client-snippet.${engine}.ts\`](./client-snippet.${engine}.ts)); use the API
key (\`x-api-key\`) for the query routes / dashboard.

## Commands

| Command                          | What it does                                  |
| -------------------------------- | --------------------------------------------- |
| \`npm run setup\`                | Create the store + first project (run once).  |
| \`npm start\`                    | Run the ingestion + query API.                |
| \`npm run new-project -- "Name"\`| Mint another project + API key.               |
| \`npm run migrate\`              | Apply store migrations.                       |

## Notes

- The collector stores events **and** metadata in one DuckDB file
  (\`./data/uptimizr.duckdb\`) — no external database, no Docker.
- \`.env\` holds your visitor-hash secret and is git-ignored. Keep it private and
  back up the DuckDB file by copying it.
- Add your app's origins to \`COLLECTOR_CORS_ORIGINS\` in \`.env\`.
`;
}
