// File-content templates for the scaffolded self-host folder. Pure string
// builders — no I/O — so they are trivially testable.

/** Engines the scaffolder can emit a client snippet for. */
export const ENGINES = ["babylon", "babylon-lite", "three", "r3f", "playcanvas", "aframe"] as const;

export type Engine = (typeof ENGINES)[number];

/** npm package a developer installs in their app for a given engine. */
export const ENGINE_PACKAGE: Record<Engine, string> = {
  babylon: "@uptimizr/babylon",
  "babylon-lite": "@uptimizr/babylon-lite",
  three: "@uptimizr/three",
  r3f: "@uptimizr/r3f",
  playcanvas: "@uptimizr/playcanvas",
  aframe: "@uptimizr/aframe",
};

const DEFAULT_PORT = 4318;

/** Port the optional analytics dashboard (`@uptimizr/dashboard`) serves on. */
export const DASHBOARD_PORT = 3000;

/** Port the optional runnable demo scene serves on (matches the default CORS origin). */
export const DEMO_PORT = 5173;

/** Pinned versions used by the browser-side demo (loaded from a CDN, no bundler). */
const BABYLON_CDN_RANGE = "9";
const UPTIMIZR_BABYLON_VERSION = "0.1.0";

/** Optional extras a developer can fold into the scaffold. */
export interface ScaffoldExtras {
  /** Include the analytics dashboard (`@uptimizr/dashboard`) for the full suite. */
  withDashboard?: boolean;
  /** Include a runnable Babylon demo scene that generates events end-to-end. */
  withDemo?: boolean;
}

/** The collector endpoint a freshly-scaffolded local self-host listens on. */
export function localEndpoint(port: number = DEFAULT_PORT): string {
  return `http://localhost:${port}`;
}

/** Browser origins the collector should trust, given the chosen extras. */
function corsOrigins(extras: ScaffoldExtras): string[] {
  // The user's own app dev server (Vite's default) and the demo both live on
  // :5173; the dashboard, when bundled, reads the query API from :3000.
  const origins = [`http://localhost:${DEMO_PORT}`];
  if (extras.withDashboard) origins.push(`http://localhost:${DASHBOARD_PORT}`);
  return origins;
}

export function renderPackageJson(
  folderName: string,
  projectName: string,
  extras: ScaffoldExtras = {},
): string {
  const scripts: Record<string, string> = {
    // First-run setup: mint the first project + API key and ensure the store
    // is migrated. The generated .env already holds the visitor-hash secret.
    setup: `uptimizr init ${JSON.stringify(projectName)}`,
    // Run the ingestion + query API (reads the generated .env).
    start: "uptimizr serve",
    "new-project": "uptimizr new-project",
    migrate: "uptimizr migrate",
  };
  const dependencies: Record<string, string> = {
    "@uptimizr/collector-server": "^0.2.1",
  };
  if (extras.withDashboard) {
    // The dashboard ships its own zero-dep static server (`uptimizr-dashboard`).
    dependencies["@uptimizr/dashboard"] = "^0.1.0";
    scripts.dashboard = `uptimizr-dashboard --port ${DASHBOARD_PORT}`;
  }
  if (extras.withDemo) {
    // A self-contained Babylon scene served on its own origin; generates events.
    scripts.demo = "node demo/serve.mjs";
  }
  const pkg = {
    name: folderName,
    version: "0.0.0",
    private: true,
    type: "module",
    description: `Uptimizr self-host for "${projectName}" (DuckDB, no Docker).`,
    scripts,
    dependencies,
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

export function renderEnv(
  secret: string,
  port: number = DEFAULT_PORT,
  extras: ScaffoldExtras = {},
): string {
  return `${[
    "# Uptimizr collector configuration (generated by create-uptimizr).",
    "# OSS default store is DuckDB — no Docker, no external database.",
    "# Keep this file private; it holds your visitor-hash secret.",
    "",
    `VISITOR_HASH_SECRET=${secret}`,
    "COLLECTOR_STORE=duckdb",
    "DUCKDB_PATH=./data/uptimizr.duckdb",
    `COLLECTOR_PORT=${port}`,
    "",
    "# Browser origins allowed to send analytics / read the query API",
    "# (comma-separated). Add your app's dev + production origins here.",
    `COLLECTOR_CORS_ORIGINS=${corsOrigins(extras).join(",")}`,
    "",
    "# All-in-one (optional): point at a static dashboard build to serve the UI",
    "# from this same process. See @uptimizr/dashboard.",
    "# COLLECTOR_DASHBOARD_DIR=./dashboard",
  ].join("\n")}\n`;
}

/**
 * A self-contained Babylon demo page (no bundler) that drives the reference
 * `@uptimizr/babylon` connector against the local collector. It uses Babylon —
 * the reference connector — regardless of the chosen client-engine, so a user
 * can see analytics flow end-to-end "in one go". It only *sends* events
 * (anonymous, key-less ingestion); view them in the dashboard.
 */
export function renderDemoHtml(port: number = DEFAULT_PORT): string {
  const endpoint = localEndpoint(port);
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Uptimizr demo scene</title>
    <style>
      :root { color-scheme: dark; }
      html, body { margin: 0; height: 100%; background: #0b0b10; color: #e7e7ea;
        font: 14px/1.5 system-ui, sans-serif; }
      #app { display: grid; grid-template-rows: auto 1fr; height: 100%; }
      header { padding: 10px 14px; border-bottom: 1px solid #23232b;
        display: flex; gap: 10px; align-items: center; flex-wrap: wrap; }
      header strong { color: #8b8bff; }
      header input { background: #14141c; border: 1px solid #2c2c38; color: inherit;
        border-radius: 6px; padding: 6px 8px; min-width: 280px; }
      header .hint { color: #9a9aa6; }
      canvas { width: 100%; height: 100%; display: block; outline: none; touch-action: none; }
      #banner { display: none; padding: 8px 14px; background: #3a2a12; color: #ffd9a0;
        border-bottom: 1px solid #5a4422; }
    </style>
    <script type="importmap">
      {
        "imports": {
          "@babylonjs/core": "https://esm.sh/@babylonjs/core@${BABYLON_CDN_RANGE}",
          "@uptimizr/babylon": "https://esm.sh/@uptimizr/babylon@${UPTIMIZR_BABYLON_VERSION}?external=@babylonjs/core"
        }
      }
    </script>
  </head>
  <body>
    <div id="app">
      <header>
        <strong>Uptimizr demo</strong>
        <label>Project ID
          <input id="projectId" placeholder="paste the id from 'npm run setup'" />
        </label>
        <span class="hint">Collector: ${endpoint}</span>
        <span class="hint">Move/click the scene, then watch the dashboard.</span>
      </header>
      <div id="banner">
        Enter the <strong>Project ID</strong> printed by <code>npm run setup</code> to start
        sending events.
      </div>
      <canvas id="renderCanvas"></canvas>
    </div>
    <script type="module">
      import {
        Engine, Scene, ArcRotateCamera, HemisphericLight, Vector3, Color3, Color4,
        MeshBuilder, StandardMaterial,
      } from "@babylonjs/core";
      import { trackScene } from "@uptimizr/babylon";

      const ENDPOINT = ${JSON.stringify(endpoint)};
      const canvas = document.getElementById("renderCanvas");
      const banner = document.getElementById("banner");
      const projectInput = document.getElementById("projectId");
      projectInput.value = localStorage.getItem("uptimizr.projectId") || "";

      const engine = new Engine(canvas, true, { preserveDrawingBuffer: true, stencil: true });
      const scene = new Scene(engine);
      scene.clearColor = new Color4(0.04, 0.04, 0.07, 1);

      const camera = new ArcRotateCamera("cam", -Math.PI / 2, Math.PI / 3, 14, Vector3.Zero(), scene);
      camera.attachControl(canvas, true);
      camera.lowerRadiusLimit = 4;
      camera.upperRadiusLimit = 40;
      new HemisphericLight("light", new Vector3(0, 1, 0), scene);

      const ground = MeshBuilder.CreateGround("ground", { width: 20, height: 20 }, scene);
      const groundMat = new StandardMaterial("groundMat", scene);
      groundMat.diffuseColor = new Color3(0.12, 0.12, 0.18);
      ground.material = groundMat;

      const palette = [
        [0.55, 0.55, 1], [1, 0.55, 0.7], [0.55, 1, 0.75], [1, 0.85, 0.45], [0.6, 0.85, 1],
      ];
      for (let i = 0; i < palette.length; i++) {
        const box = MeshBuilder.CreateBox("box-" + (i + 1), { size: 1.6 }, scene);
        box.position.x = (i - (palette.length - 1) / 2) * 3;
        box.position.y = 1;
        const mat = new StandardMaterial("mat-" + i, scene);
        const [r, g, b] = palette[i];
        mat.diffuseColor = new Color3(r, g, b);
        box.material = mat;
      }

      engine.runRenderLoop(() => scene.render());
      window.addEventListener("resize", () => engine.resize());

      let connector = null;
      function applyProject() {
        const projectId = projectInput.value.trim();
        if (connector) { connector.dispose(); connector = null; }
        if (!projectId) { banner.style.display = "block"; return; }
        banner.style.display = "none";
        localStorage.setItem("uptimizr.projectId", projectId);
        connector = trackScene(scene, {
          projectId,
          endpoint: ENDPOINT,
          capture: { meshInteractions: true },
        });
      }
      projectInput.addEventListener("change", applyProject);
      applyProject();
    </script>
  </body>
</html>
`;
}

/** Zero-dependency static server for the demo folder (Node http/fs only). */
export function renderDemoServer(demoPort: number = DEMO_PORT): string {
  return `// Minimal zero-dependency static server for the Uptimizr demo scene.
// Serves this folder on http://localhost:\${PORT} (default ${demoPort}, matching
// the collector's allowed CORS origin). Node http/fs only — no install needed.
import { createReadStream, existsSync, statSync } from "node:fs";
import { createServer } from "node:http";
import { extname, join, normalize, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL(".", import.meta.url)));
const PORT = Number(process.env.DEMO_PORT ?? process.env.PORT ?? ${demoPort});
const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
};

function resolveSafe(urlPath) {
  const decoded = decodeURIComponent(urlPath.split("?")[0].split("#")[0]);
  const rel = normalize(decoded).replace(/^(\\.\\.[/\\\\])+/, "");
  const abs = join(ROOT, rel === "/" || rel === "" ? "index.html" : rel);
  if (abs !== ROOT && !abs.startsWith(ROOT + "/")) return null;
  return abs;
}

createServer((req, res) => {
  const abs = resolveSafe(req.url ?? "/");
  if (!abs || !existsSync(abs) || !statSync(abs).isFile()) {
    res.writeHead(404, { "content-type": "text/plain" });
    res.end("Not found");
    return;
  }
  res.writeHead(200, {
    "content-type": MIME[extname(abs)] ?? "application/octet-stream",
    "cache-control": "no-store",
  });
  createReadStream(abs).pipe(res);
}).listen(PORT, () => {
  console.log("Uptimizr demo scene: http://localhost:" + PORT);
});
`;
}

export function renderGitignore(): string {
  return `${["node_modules/", ".env", "data/"].join("\n")}\n`;
}

/** A ready-to-paste client snippet for the chosen engine. */
export function renderClientSnippet(engine: Engine, port: number = DEFAULT_PORT): string {
  const endpoint = localEndpoint(port);
  const pkg = ENGINE_PACKAGE[engine];
  const header = [
    `// Wire Uptimizr into your ${engine} app.`,
    `// Install the connector in your app:  npm install ${pkg}`,
    `// Replace PROJECT_ID with the id printed by \`npm run setup\`.`,
    "",
  ].join("\n");

  switch (engine) {
    case "babylon":
      return `${header}import { trackScene } from "${pkg}";

trackScene(scene, {
  projectId: "PROJECT_ID",
  endpoint: "${endpoint}",
});
`;
    case "babylon-lite":
      return `${header}import { trackScene } from "${pkg}";

trackScene(scene, camera, canvas, {
  projectId: "PROJECT_ID",
  endpoint: "${endpoint}",
});
`;
    case "three":
      return `${header}import { trackScene } from "${pkg}";

trackScene(scene, camera, renderer, {
  projectId: "PROJECT_ID",
  endpoint: "${endpoint}",
});
`;
    case "playcanvas":
      return `${header}import { trackScene } from "${pkg}";

trackScene(app, cameraEntity, {
  projectId: "PROJECT_ID",
  endpoint: "${endpoint}",
});
`;
    case "r3f":
      return `${header}import { Uptimizr } from "${pkg}";

// Render inside your <Canvas> tree:
//   <Canvas>
//     <Uptimizr projectId="PROJECT_ID" endpoint="${endpoint}" />
//     {/* ...your scene... */}
//   </Canvas>
`;
    case "aframe":
      return `${header}// Import once to register the component, then add the attribute to <a-scene>:
import "${pkg}";

// <a-scene uptimizr="projectId: PROJECT_ID; collector: ${endpoint}">
//   <!-- ...your scene... -->
// </a-scene>
`;
  }
}

export function renderReadme(
  folderName: string,
  projectName: string,
  engine: Engine,
  port: number = DEFAULT_PORT,
  extras: ScaffoldExtras = {},
): string {
  const endpoint = localEndpoint(port);
  const suiteRows = [
    extras.withDemo
      ? `| \`npm run demo\`                  | Serve a runnable Babylon demo scene (http://localhost:${DEMO_PORT}). |`
      : "",
    extras.withDashboard
      ? `| \`npm run dashboard\`             | Serve the analytics dashboard (http://localhost:${DASHBOARD_PORT}). |`
      : "",
  ]
    .filter(Boolean)
    .join("\n");

  const suiteSection =
    extras.withDemo || extras.withDashboard
      ? `

## Test everything in one go

This scaffold includes the full suite. In separate terminals:

\`\`\`bash
npm start          # 1) collector — ingestion + query API on ${endpoint}
${extras.withDemo ? `npm run demo       # 2) demo scene on http://localhost:${DEMO_PORT} — generates events\n` : ""}${extras.withDashboard ? `npm run dashboard  # ${extras.withDemo ? "3" : "2"}) dashboard on http://localhost:${DASHBOARD_PORT} — view the analytics\n` : ""}\`\`\`
${
  extras.withDemo
    ? `
Open the demo, paste the **projectId** from \`npm run setup\`, then orbit/click the
scene to generate camera, pointer, and mesh events.`
    : ""
}${
          extras.withDashboard
            ? `
In the dashboard's connection bar, enter the **endpoint** (\`${endpoint}\`) and the
**API key** from \`npm run setup\` to read the collected analytics.`
            : ""
        }
`
      : "";

  return `# ${folderName}

A Docker-free, single-file (DuckDB) self-host of the Uptimizr OSS 3D-analytics
collector, scaffolded for **${projectName}**.

## Quick start

\`\`\`bash
npm install      # install the collector
npm run setup    # mint your first project + API key (printed once)
npm start        # ingestion + query API on ${endpoint}
\`\`\`

\`npm run setup\` prints a **projectId**, a one-time **API key**, and the
**endpoint**. Give the projectId + endpoint to your app's connector (see
[\`client-snippet.${engine}.ts\`](./client-snippet.${engine}.ts)); use the API
key (\`x-api-key\`) for the query routes / dashboard.

## Commands

| Command                          | What it does                                  |
| -------------------------------- | --------------------------------------------- |
| \`npm run setup\`                | Create the store + first project (run once).  |
| \`npm start\`                    | Run the ingestion + query API.                |
| \`npm run new-project -- "Name"\`| Mint another project + API key.               |
| \`npm run migrate\`              | Apply store migrations.                       |${suiteRows ? `\n${suiteRows}` : ""}
${suiteSection}
## Notes

- The collector stores events **and** metadata in one DuckDB file
  (\`./data/uptimizr.duckdb\`) — no external database, no Docker.
- \`.env\` holds your visitor-hash secret and is git-ignored. Keep it private and
  back up the DuckDB file by copying it.
- Add your app's origins to \`COLLECTOR_CORS_ORIGINS\` in \`.env\`.
`;
}
