import {
  createDuckdbClient,
  duckdbCreateApiKey,
  duckdbCreateProject,
  migrateDuckdb,
  readDbSettings,
} from "@uptimizr/db";
import {
  createApiKey as chCreateApiKey,
  createClickhouseClient,
  createProject as chCreateProject,
  migrateClickhouse,
} from "@uptimizr/db-clickhouse";
import {
  createApiKey as msCreateApiKey,
  createMssqlClient,
  createProject as msCreateProject,
  ensureMssqlDatabase,
  migrateMssql,
  resolveMssqlConfig,
} from "@uptimizr/db-mssql";
import {
  createApiKey as pgCreateApiKey,
  createPostgresClient,
  createProject as pgCreateProject,
  migratePostgres,
} from "@uptimizr/db-postgres";

/**
 * The persistent stores the `uptimizr` CLI can bootstrap (`init` / `new-project`
 * / `migrate`). Mirrors the `COLLECTOR_STORE` values `serve` accepts, minus
 * `memory`, which keeps nothing between processes and so has nothing to
 * initialise.
 */
export const CLI_STORES = ["duckdb", "postgres", "mssql", "clickhouse"] as const;

export type CliStoreKind = (typeof CLI_STORES)[number];

/**
 * The slice of a store the CLI needs: mint projects and API keys against an
 * already-migrated store, then release the connection. Each engine's
 * `createProject` / `createApiKey` live in its own package; this narrows them
 * to one engine-neutral shape so the commands stay store-agnostic.
 */
export interface CliStore {
  createProject(name: string): Promise<{ id: string; name: string }>;
  /** Issue a query-capable API key; the plaintext is returned exactly once. */
  createApiKey(projectId: string): Promise<{ key: string }>;
  close(): Promise<void>;
}

/**
 * Normalise `COLLECTOR_STORE` for the CLI: unset (or blank) selects the OSS
 * DuckDB default; `memory` and unknown values throw with an actionable message
 * rather than silently bootstrapping the wrong store.
 */
export function resolveCliStoreKind(env: NodeJS.ProcessEnv = process.env): CliStoreKind {
  const value = env.COLLECTOR_STORE?.trim() || "duckdb";
  if ((CLI_STORES as readonly string[]).includes(value)) return value as CliStoreKind;
  if (value === "memory") {
    throw new Error(
      "COLLECTOR_STORE=memory keeps nothing between runs, so there is no store to initialise. " +
        "Seed its project and key with COLLECTOR_MEMORY_PROJECT_ID / COLLECTOR_MEMORY_API_KEY instead.",
    );
  }
  throw new Error(`Unknown COLLECTOR_STORE "${value}". Expected one of: ${CLI_STORES.join(", ")}.`);
}

/**
 * Connection variables `init` copies from the environment into a fresh `.env`
 * (when set), so the store it bootstrapped is the one `serve` opens next run.
 */
const STORE_ENV_KEYS: Record<CliStoreKind, readonly string[]> = {
  duckdb: ["DUCKDB_PATH"],
  postgres: ["POSTGRES_URL", "DATABASE_URL", "POSTGRES_SCHEMA", "POSTGRES_POOL_MAX"],
  mssql: [
    "MSSQL_URL",
    "MSSQL_SERVER",
    "MSSQL_PORT",
    "MSSQL_DATABASE",
    "MSSQL_USER",
    "MSSQL_PASSWORD",
    "MSSQL_ENCRYPT",
    "MSSQL_TRUST_SERVER_CERTIFICATE",
    "MSSQL_POOL_MAX",
  ],
  clickhouse: ["CLICKHOUSE_URL", "CLICKHOUSE_DATABASE", "CLICKHOUSE_USER", "CLICKHOUSE_PASSWORD"],
};

/**
 * The `.env` `uptimizr init` writes when none exists: the secret, the selected
 * store, and whichever of that store's connection variables were set.
 */
export function renderEnv(
  secret: string,
  store: CliStoreKind,
  env: NodeJS.ProcessEnv = process.env,
): string {
  const lines = [
    "# Uptimizr collector configuration (generated by 'uptimizr init').",
    store === "duckdb"
      ? "# OSS default store is DuckDB — no Docker, no external database."
      : `# Store: ${store} — connection settings captured when 'uptimizr init' ran.`,
    "",
    `VISITOR_HASH_SECRET=${secret}`,
    `COLLECTOR_STORE=${store}`,
  ];
  for (const key of STORE_ENV_KEYS[store]) {
    const value = env[key];
    if (value !== undefined) lines.push(`${key}=${value}`);
  }
  if (store === "duckdb" && env.DUCKDB_PATH === undefined) {
    lines.push("DUCKDB_PATH=./data/uptimizr.duckdb");
  }
  lines.push(`COLLECTOR_PORT=${env.COLLECTOR_PORT ?? 4318}`);
  return `${lines.join("\n")}\n`;
}

/**
 * Open the store selected by `COLLECTOR_STORE` and apply its migrations, the
 * same way `serve` does on boot, then hand back the metadata helpers the CLI
 * commands need. Connection settings come from the same env variables as
 * `serve` (`DUCKDB_PATH`, `POSTGRES_URL`, `MSSQL_URL`, `CLICKHOUSE_*`, …), so a
 * project minted here is the one the running collector will resolve.
 */
export async function openCliStore(env: NodeJS.ProcessEnv = process.env): Promise<CliStore> {
  const kind = resolveCliStoreKind(env);
  const settings = readDbSettings(env);

  switch (kind) {
    case "duckdb": {
      const db = await createDuckdbClient(settings.duckdb.path);
      await migrateDuckdb(db);
      return {
        createProject: (name) => duckdbCreateProject(db, name),
        createApiKey: (projectId) => duckdbCreateApiKey(db, projectId),
        close: () => db.close(),
      };
    }
    case "postgres": {
      const pgc = createPostgresClient(settings.postgres);
      await migratePostgres(pgc, settings.postgres);
      return {
        createProject: (name) => pgCreateProject(pgc, name),
        createApiKey: (projectId) => pgCreateApiKey(pgc, projectId),
        close: () => pgc.close(),
      };
    }
    case "mssql": {
      const database = resolveMssqlConfig(settings.mssql).database ?? settings.mssql.database;
      await ensureMssqlDatabase(settings.mssql, database);
      const msc = createMssqlClient(settings.mssql);
      await migrateMssql(msc);
      return {
        createProject: (name) => msCreateProject(msc, name),
        createApiKey: (projectId) => msCreateApiKey(msc, projectId),
        close: () => msc.close(),
      };
    }
    case "clickhouse": {
      const ch = createClickhouseClient(settings.clickhouse);
      await migrateClickhouse(ch, settings.clickhouse);
      return {
        createProject: (name) => chCreateProject(ch, name),
        createApiKey: (projectId) => chCreateApiKey(ch, projectId),
        close: () => ch.close(),
      };
    }
  }
}
