/**
 * `@uptimizr/schema` — the single source of truth for Uptimizr analytics events.
 *
 * Every producer (SDKs) and consumer (collector, replay, dashboard) imports event
 * shapes from here. Never redefine event types elsewhere.
 *
 * See the package README for the event catalog and how to add new event types.
 */

export { SCHEMA_VERSION, DEFAULT_SCENE_ID, EVENT_TYPES, type EventType } from "./constants.js";

export { LIMITS, boundedRecord } from "./limits.js";

export {
  vec3Schema,
  vec2Schema,
  quatSchema,
  normalized2Schema,
  epochMsSchema,
  sceneIdSchema,
  type Vec3,
  type Vec2,
  type Quat,
  type Normalized2,
  type SceneId,
} from "./primitives.js";

export {
  envelopeSchema,
  envelopeShape,
  pageMetaSchema,
  type Envelope,
  type PageMeta,
} from "./envelope.js";

export {
  // registry + union
  eventSchemaList,
  anyEventSchema,
  eventSchemaByType,
  type AnyEvent,
  // factory
  defineEvent,
  // per-event schemas + types
  sessionStartSchema,
  deviceSchema,
  sceneMetaSchema,
  cameraKindSchema,
  sessionUserSchema,
  userTraitValueSchema,
  connectorSchema,
  graphicsApiSchema,
  graphicsBackendSchema,
  shadingLanguageSchema,
  graphicsSchema,
  sessionEndSchema,
  framePerfSchema,
  cameraSampleSchema,
  nodeTransformSchema,
  pointerMoveSchema,
  pointerClickSchema,
  pointerDownSchema,
  pointerUpSchema,
  cameraGestureSchema,
  cameraGestureKindSchema,
  meshInteractionSchema,
  meshInteractionKindSchema,
  assetLoadSchema,
  sceneChangeSchema,
  inputSourceSchema,
  handednessSchema,
  raySchema,
  inputSourceShape,
  inputActionSchema,
  arPlacementSchema,
  arPlacementSurfaceSchema,
  customSchema,
  customPropValueSchema,
  capabilityChangeSchema,
  capabilityChangeKindSchema,
  graphicsDiagnosticSchema,
  graphicsDiagnosticSeveritySchema,
  graphicsDiagnosticCategorySchema,
  type Device,
  type SceneMeta,
  type CameraKind,
  type SessionUser,
  type UserTraitValue,
  type Connector,
  type GraphicsApi,
  type GraphicsBackend,
  type ShadingLanguage,
  type Graphics,
  type SessionStartEvent,
  type SessionEndEvent,
  type FramePerfEvent,
  type CameraSampleEvent,
  type NodeTransformEvent,
  type PointerMoveEvent,
  type PointerClickEvent,
  type PointerDownEvent,
  type PointerUpEvent,
  type CameraGestureEvent,
  type CameraGestureKind,
  type MeshInteractionEvent,
  type MeshInteractionKind,
  type AssetLoadEvent,
  type SceneChangeEvent,
  type InputSource,
  type Handedness,
  type Ray,
  type InputActionEvent,
  type ArPlacementEvent,
  type ArPlacementSurface,
  type CustomEvent,
  type CustomPropValue,
  type CapabilityChangeEvent,
  type CapabilityChangeKind,
  type GraphicsDiagnosticEvent,
  type GraphicsDiagnosticSeverity,
  type GraphicsDiagnosticCategory,
} from "./events/index.js";

export {
  collectRequestSchema,
  collectResponseSchema,
  type CollectRequest,
  type CollectResponse,
} from "./batch.js";

export {
  SCENE_PROXY_VERSION,
  aabbSchema,
  upAxisSchema,
  sceneProxyKindSchema,
  meshTransformSchema,
  sceneProxyMeshSchema,
  sceneProxySchema,
  type Aabb,
  type UpAxis,
  type SceneProxyKind,
  type MeshTransform,
  type SceneProxyMesh,
  type SceneProxy,
} from "./sceneProxy.js";

export {
  regionIdSchema,
  sceneRegionSchema,
  sceneRegionsSchema,
  type RegionId,
  type SceneRegion,
  type SceneRegions,
} from "./sceneRegion.js";

export {
  coordinateHandednessSchema,
  coordinateSystemSchema,
  type CoordinateHandedness,
  type CoordinateSystem,
} from "./coordinateSystem.js";

export {
  FUNNEL_CONFIG_VERSION,
  funnelStepEventTypeSchema,
  funnelStepSchema,
  funnelStepsSchema,
  funnelConfigSchema,
  type FunnelStepEventType,
  type FunnelStep,
  type FunnelSteps,
  type FunnelConfig,
} from "./funnel.js";

export {
  BUS_BACKED_PREDICATE_KINDS,
  MAX_COOLDOWN_MS,
  MAX_EVALUATE_EVERY_MS,
  MAX_EVALUATE_WINDOW_MS,
  MIN_EVALUATE_EVERY_MS,
  MIN_EVALUATE_WINDOW_MS,
  SUBSCRIPTION_CONFIG_VERSION,
  SUBSCRIPTION_PREDICATE_KINDS,
  anomalyPredicateSchema,
  comparisonOpSchema,
  cooldownSchema,
  evaluateEverySchema,
  evaluateWindowSchema,
  formatDurationMs,
  isBusBackedPredicate,
  moversPredicateSchema,
  newValueDimensionSchema,
  newValuePredicateSchema,
  parseDurationMs,
  presencePredicateSchema,
  sseDeliverySchema,
  subscriptionBucketSchema,
  subscriptionDeliverySchema,
  subscriptionEvaluateSchema,
  subscriptionFiltersSchema,
  subscriptionFiringSchema,
  subscriptionPatchSchema,
  subscriptionPredicateSchema,
  subscriptionSchema,
  thresholdPredicateSchema,
  webhookDeliverySchema,
  type ComparisonOp,
  type NewValueDimension,
  type Subscription,
  type SubscriptionBucket,
  type SubscriptionDelivery,
  type SubscriptionEvaluate,
  type SubscriptionFilters,
  type SubscriptionFiring,
  type SubscriptionPatch,
  type SubscriptionPredicate,
  type SubscriptionPredicateKind,
} from "./subscription.js";
